generator:
  WIDTH: 40
  HEIGHT: 40
  FORMAT: "png"
  CHARTSET: "utf-8"


spring:
  datasource:
    username: chuangxin
    password: chuangxin
    url: jdbc:mysql://localhost:3306/数据库?useUnicode=true&useSSL=false&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

mybatis:
  configuration:
    map-underscore-to-camel-case: true